# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
# Mod properties
mod_version=1.0.8
maven_group=com.frikinjay
archives_name=mobstacker-26.1.2
enabled_platforms=fabric
# Minecraft properties
minecraft_version=26.1.2
# Dependencies
fabric_loader_version=0.16.7
